### ISSUE TITLE
Build error because of new flate2 version

### ISSUE THREAD

**Issue by KevinBalz** [mattyhall/rs-tiled#1]
flate2 recently updated to  "0.2.0" and uses the new std::io.
Wheter the Cargo.toml could be updated to use version 0.1.8 of flate2
or rs-tiled has to be changed to use the new std::io.
  
Also the flate2 module reader has been renamed to read.
  
See: https://travis-ci.org/mattyhall/rs-tiled/builds/50744832

**Comment by mattyhall** [comment]
Thanks for the report! I've updated the code to use the new std::io. Unfortunately it got rid of the `read_u32_le` methods so I've had to roll that myself.

Travis still says the build is failing because the latest cargo in rust nightly is broken. It works on my machine though.


Cheers!

**Comment by KevinBalz** [comment]
Thanks for fixing it so fast!
Compiles and works as expected.

Cheers!
