### ISSUE TITLE
since tiled 1.9 object type is renamed into class

### ISSUE THREAD

**Issue by gui1117** [mattyhall/rs-tiled#234]
As written in https://www.mapeditor.org/2022/06/25/tiled-1-9-released.html

> Unified Custom Types
> 
> Object Types have been merged into the Property Types, now simply called “Custom Types”. This means custom classes can now have a color and can be used as “object type”. If your project refers to an object types file, these types will be automatically imported as custom classes. If you used globally stored object types before, they can be manually imported to your project.
> 
> In addition, the “Type” property previously available only for objects and tiles is now available for all data types as the new “Class” property. For consistency, this value is written out as “class” also for objects and tiles, but a project-wide compatibility option is provided to make it still write out as “type”:

Maybe rs-tiled should support the `class` attribute by default, or just automatically read the class into obj_type.
Anyhow for now I will use the compatibility option of tiled

**Comment by bjorn** [comment]
Yeah, I should really have been a little more pro-active here, ideally there would have been a new `rs-tiled` release that looks for the "class" attribute too. Oh well, sometime soon, hopefully.

**Comment by barthap** [comment]
If anybody needs a hotfix, I patched this myself ([commit](https://github.com/barthap/rs-tiled/commit/50f9dae34e480d6504fe5d3d912537f41e1c3459)), not sure if I should open a PR or if you'd like to resolve it another way.

**Comment by aleokdev** [comment]
A PR against `current` would be most welcome!

**Comment by barthap** [comment]
Actually, I found out, that layers (all kinds of them?) and maps can have a `class` property too.

So my PR only fixes this for existing entities which previously had `type`. I can add it to the others, but how the property should be named? I thought about `map_type` etc.. to keep the convention, but for layers there is already a (private) `layer_type` so I'm not sure how to name it.
