### ISSUE TITLE
Optional GIDs feature

### ISSUE THREAD

**Issue by aleokdev** [mattyhall/rs-tiled#239]
Probably the biggest reason people from <=0.9.5 aren't switching over to newer versions is that they rely on GIDs. Even if they are an internal detail of the TMX format, I'm beginning to believe removing them was a mistake. Even though they aren't reliable and may change when editing the map, they do function well by assigning unique numbers to tiles used within a map, which may be helpful when rendering or working on small projects.

Maybe we should introduce them again as an optional feature?

**Comment by bjorn** [comment]
Hmm, in all the examples I've seen, the removal of GIDs from the public API has actually simplified the logic. Is there any public project out there where we can see the GIDs being an advantage?

I still don't know Rust well enough to judge whether it is doable to support this as optional feature. I especially worry that it will get complicated to support this alongside a future modification feature.
