### ISSUE TITLE
Default zstd feature is unhelpful for wasm builds

### ISSUE THREAD

**Issue by jdm** [mattyhall/rs-tiled#240]
Out of the box, adding tiled as a dependency of my project broke my WASM builds because zstd's default build does not support it. While I eventually learned that zstd is an optional feature in tiled, this does not appear to be documented anywhere, and there aren't good interfaces for discovering crate features.

I've seen #228, and I have a couple possibilities to make the default experience better:
* keep zstd as an optional feature but default disabled
* replace zstd with another implementation that supports WASM ([branch that implements this](https://github.com/jdm/rs-tiled/tree/ruzstd))
* expose zstd's `wasm` crate feature somehow and document how to build for WASM? This is the least thought through of the alternatives because I haven't looked into it at all; I just saw that it exists.
* clearly document how to get a wasm-capable build (and the limitations around embedded tilesets), but otherwise make no changes to the status quo

**Comment by aleokdev** [comment]
Sorry for the late reply. I'll see what we can do about WASM this week as it seems like it has lots of demand by the crate users. Maybe some FAQs and a gotchas section would suffice, but I'll also think about the other options as well, thanks for the comments!

**Comment by bjorn** [comment]
If `zstd` has a `wasm` crate feature, it seems the most sensible thing would be to add a `wasm` crate feature to `rs-tiled` as well that automatically enables this. That should be doable, right?
