### ISSUE TITLE
Map::get_tileset_by_gid doesn't work for GIDs equal to the tileset's first_gid

### ISSUE THREAD

**Issue by Phrohdoh** [mattyhall/rs-tiled#25]
`map.get_tileset_by_gid(1)` will always return None.

I am pretty sure that https://github.com/mattyhall/rs-tiled/blob/d5eaab8b89a9d2e667e670225c802c0f5de017fe/src/lib.rs#L276 needs to check `... && tileset.first_gid <= gid`.

**Comment by tatref** [comment]
Fixed by #26 a while ago
