### ISSUE TITLE
Nicer way to iterate over layers of a given type

### ISSUE THREAD

**Issue by deifactor** [mattyhall/rs-tiled#255]
Right now if you want to iterate over all layers of a given type, you have to do something like

```rs
map
    .layers()
    .filter_map(|layer| match layer.layer_type() {
        tiled::LayerType::TileLayer(TileLayer::Finite(layer)) => Some(layer),
        _ => None,
    })
```

Maybe it'd make sense to pull those functions into methods on `Layer`:

```rs
impl Layer {
  // name suggestions welcome
  pub fn into_finite_tile_layer(self) -> Option<FiniteTileLayer> {
    match self.layer_type() {
          tiled::LayerType::TileLayer(TileLayer::Finite(layer)) => Some(layer),
          _ => None,
    }
  }
}
```

(and similar for all the others) so you can just write

```rs
map
    .layers()
    .filter_map(Layer::into_finite_tile_layer)
```

Or, alternately, just have a `Map::finite_tile_layers(&self)`  that does this; less boilerplate to use, more boilerplate to implement.

**Comment by bjorn** [comment]
Seems very similar to the change proposed in #235. It is currently tagged "indecisive", maybe you can help make a decision. :-)

**Comment by deifactor** [comment]
Oops, yes, this is really a dupe of #235.
