### ISSUE TITLE
get rotaion of tile

### ISSUE THREAD

**Issue by LuckyTurtleDev** [mattyhall/rs-tiled#269]
It is possible to get the rotation of a tile?
I was not able to find this at the doc. The [Map](https://docs.rs/tiled/latest/tiled/struct.Map.html) has a global  [Orientation](https://docs.rs/tiled/latest/tiled/enum.Orientation.html), but I don't see an option to get the the Orientation per tile, how Tield does also support (see below).

![image](https://github.com/mapeditor/rs-tiled/assets/44570204/598abcfc-8945-49af-bf8f-8fc967337f85)

**Comment by aleokdev** [comment]
You can get its flip bits directly from LayerTile: https://docs.rs/tiled/latest/tiled/struct.LayerTileData.html
From there you can calculate the corresponding rotation. IIRC I don't think Tiled has a rotation option per tile, only these flip bits

**Comment by LuckyTurtleDev** [comment]
Thanks for the fast response. I have over look that [LayerTile](https://docs.rs/tiled/latest/tiled/struct.LayerTileData.html) impl Deref LayerTileData.

**Comment by aleokdev** [comment]
Related to #212
