### ISSUE TITLE
Unsigned indecies for getting a tile

### ISSUE THREAD

**Issue by magras** [mattyhall/rs-tiled#275]
Right now, I have to cast the coordinates during iteration over tiles:

```
fn iterate_over_tiles(layer: &FiniteTileLayer) {
    for y in 0..layer.height() {
        for x in 0..layer.width() {
            if let Some(tile) = layer.get_tile(x as i32, y as i32) {
                ...
            }
        }
    }
}
```

Looking around briefly, I see no apparent reason for this discrepancy. Does it make sense to switch to `u32` in `FiniteTileLayer::get_tile`?

**Comment by aleokdev** [comment]
It's using i32 for consistency with infinite tile layers, which can have negative tile positions: https://docs.rs/tiled/latest/tiled/struct.InfiniteTileLayer.html
We _could_ change it, but I don't think it's worth the correctness since it would be a breaking change (and it'd also be inconsistent)
