### ISSUE TITLE
Not getting all of the tiles when iterating?

### ISSUE THREAD

**Issue by feelingsonice** [mattyhall/rs-tiled#280]
Testing this on a hex grid with 5 tiles placed. From `(0,0)` to `(4,0)`. Left most tile you see is at `(0,0)`

<img width="633" alt="Screenshot 2023-12-22 at 1 33 46 AM" src="https://github.com/mapeditor/rs-tiled/assets/42384776/2e262edc-dbc5-44e5-882e-067ce3efb431">

I'm want to iterate through the tiles placed on the map and note down their positions. When I try:

```rust
    if let TileLayer::Infinite(layer) = map.get_layer(0).unwrap().as_tile_layer().unwrap() {
        for chunk in layer.chunks() {
            println!("{:?}", chunk);
            println!("#################")
        }
    }
```

I got only 1 chunk with `width: 2` and `height: 2` positioned at `(0,0)`. Where are the rest of the tiles? A more general question is what's the easiest way to iterate through all of the tiles on an infinite layer?

**Comment by bjorn** [comment]
> I got only 1 chunk with `width: 2` and `height: 2` positioned at `(0,0)`. Where are the rest of the tiles? A more general question is what's the easiest way to iterate through all of the tiles on an infinite layer?

Hmm, chunks actually don't have an individual width and height, so I'm not sure which width and height you're referring to there? Since chunks are currently always 16x16, it is at least expected that for that map there is only a single chunk.

The documentation for [`InfiniteTileLayer::chunks`](https://docs.rs/tiled/0.11.2/tiled/struct.InfiniteTileLayer.html#method.chunks) provides an example showing how to iterate the tiles in a chunk.

**Comment by feelingsonice** [comment]
@bjorn I see. Thanks for the clarification. 

An unrelated question for you. I want to load a tmx map async. What would be the easiest way to do that? an async reader?

**Comment by aleokdev** [comment]
> I want to load a tmx map async. What would be the easiest way to do that? an async reader?

Since the crate has no async support (it'd require an entire rewrite of the interface) the best option is to either block or load the map on another thread and then send it over via a channel or some other send  mechanism.

**Comment by bjorn** [comment]
@feelingsonice I guess we can close this issue now, but I'm still curious, where did you see the "`width: 2` and `height: 2`" reported in the original question?

**Comment by feelingsonice** [comment]
![Screenshot 2023-12-26 at 1 08 20 PM](https://github.com/mapeditor/rs-tiled/assets/42384776/14aeb2b0-48f3-44ed-9568-57c8e5bb1c33)

I think it was referring to the width and height in that screenshot. But I see now that the chunk width and height are 16x16

**Comment by bjorn** [comment]
> I think it was referring to the width and height in that screenshot.

Hmm, yes, that looks quite confusing. Since the map is marked as Infinite, the map's Width and Height properties are meaningless / not actually used. Would be nice to reflect this better in Tiled's UI.
