### ISSUE TITLE
`object.id()` returns a GID

### ISSUE THREAD

**Issue by aleokdev** [mattyhall/rs-tiled#302]
While refactoring my sokoban clone I found out that `object.id()` actually returns a GID, not a local ID. This may cause confusion, and since the tile ID (and other info such as tileset) can be obtained anyways from `get_tile()` I propose we just deprecate the `id()` function altogether, and document the actual way to obtain the tile ID/tileset.

**Comment by bjorn** [comment]
That sounds broken, but can you refer to the code? To me it seems it should really return the ID of the object, as expected:

https://github.com/mapeditor/rs-tiled/blob/f86e079fc2ca9de362ed576d2ae8c21636bf479d/src/objects.rs#L203-L210

with that ID being initialized based on the `id` attribute:

https://github.com/mapeditor/rs-tiled/blob/f86e079fc2ca9de362ed576d2ae8c21636bf479d/src/objects.rs#L232-L235

Though `ObjectTileData` does provide an `id()` as well, that is actually the local tile ID and not a GID either:

https://github.com/mapeditor/rs-tiled/blob/f86e079fc2ca9de362ed576d2ae8c21636bf479d/src/objects.rs#L39-L44

**Comment by aleokdev** [comment]
This is embarassing, I completely forgot objects have an ID too... That would explain why they're unique per map. Oops 😅 Sorry for the confusion
