### ISSUE TITLE
Objects x/y/width/height should not be of type i32

### ISSUE THREAD

**Issue by sinistersnare** [mattyhall/rs-tiled#8]
The current Object enum contains the different kind of Objects, but their position and size values contain i32's ([see here](https://github.com/mattyhall/rs-tiled/blob/46581f08d5bd88c89beeccc104d13807cb47dc95/src/lib.rs#L376)). Looking at some generated code from the tiled map editor, I am getting floating point numbers, which is not making me happy :(

I would say it should take f32, and am probably gonna make a PR tomorrow, but wanted to get some input otherwise.

**Comment by mattyhall** [comment]
You're correct, sorry about that. I'm pretty sure f32 will be fine if you want to do that. 

Thanks

**Comment by mattyhall** [comment]
Sorry for closing it just then - fat fingers and a thin phone!

**Comment by sinistersnare** [comment]
Should have been closed when #9 was closed
